/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OaaxRouteImport } from './routes/oaax'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as InviteIndexRouteImport } from './routes/invite.index'
import { Route as SelbstauskunftTokenRouteImport } from './routes/selbstauskunft.$token'
import { Route as PlatformUsersRouteImport } from './routes/platform.users'
import { Route as PlatformSettingsRouteImport } from './routes/platform.settings'
import { Route as PlatformSecurityRouteImport } from './routes/platform.security'
import { Route as PlatformModulesRouteImport } from './routes/platform.modules'
import { Route as PlatformFeedbackRouteImport } from './routes/platform.feedback'
import { Route as PlatformDomainsRouteImport } from './routes/platform.domains'
import { Route as PlatformCommercialRouteImport } from './routes/platform.commercial'
import { Route as PlatformActivityRouteImport } from './routes/platform.activity'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as FinanzierungTokenRouteImport } from './routes/finanzierung.$token'
import { Route as BankPaketTokenRouteImport } from './routes/bank-paket.$token'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReservationsRouteImport } from './routes/_app/reservations'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppNdasRouteImport } from './routes/_app/ndas'
import { Route as AppMediaRouteImport } from './routes/_app/media'
import { Route as AppMatchingRouteImport } from './routes/_app/matching'
import { Route as AppMandatesRouteImport } from './routes/_app/mandates'
import { Route as AppLeadsRouteImport } from './routes/_app/leads'
import { Route as AppGeneratedDocumentsRouteImport } from './routes/_app/generated-documents'
import { Route as AppFeedbackRouteImport } from './routes/_app/feedback'
import { Route as AppExposesRouteImport } from './routes/_app/exposes'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCommissionsRouteImport } from './routes/_app/commissions'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppChecklistsRouteImport } from './routes/_app/checklists'
import { Route as AppAppointmentsRouteImport } from './routes/_app/appointments'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as PlatformTenantsIndexRouteImport } from './routes/platform.tenants.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppPropertiesIndexRouteImport } from './routes/_app/properties.index'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads.index'
import { Route as AppFinancingIndexRouteImport } from './routes/_app/financing.index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients.index'
import { Route as PlatformTenantsAgencyIdRouteImport } from './routes/platform.tenants.$agencyId'
import { Route as ApiPublicPortalWebhookRouteImport } from './routes/api/public/portal-webhook'
import { Route as AppSettingsWhiteLabelRouteImport } from './routes/_app/settings.white-label'
import { Route as AppSettingsVideoRouteImport } from './routes/_app/settings.video'
import { Route as AppSettingsTrashRouteImport } from './routes/_app/settings.trash'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings.profile'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings.notifications'
import { Route as AppSettingsModulesRouteImport } from './routes/_app/settings.modules'
import { Route as AppSettingsEsignRouteImport } from './routes/_app/settings.esign'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app/settings.company'
import { Route as AppSettingsCategoriesRouteImport } from './routes/_app/settings.categories'
import { Route as AppSettingsCalendarRouteImport } from './routes/_app/settings.calendar'
import { Route as AppSettingsBrandkitRouteImport } from './routes/_app/settings.brandkit'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings.billing'
import { Route as AppSettingsBanksRouteImport } from './routes/_app/settings.banks'
import { Route as AppPropertiesIdRouteImport } from './routes/_app/properties.$id'
import { Route as AppMeetRoomRouteImport } from './routes/_app/meet.$room'
import { Route as AppLeadsIdRouteImport } from './routes/_app/leads.$id'
import { Route as AppFinancingIdRouteImport } from './routes/_app/financing.$id'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicMsCalendarWorkerRouteImport } from './routes/api/public/ms-calendar/worker'
import { Route as ApiPublicMsCalendarNotificationsRouteImport } from './routes/api/public/ms-calendar/notifications'
import { Route as ApiPublicMsCalendarCallbackRouteImport } from './routes/api/public/ms-calendar/callback'
import { Route as ApiPublicBankPaketTokenRouteImport } from './routes/api/public/bank-paket.$token'
import { Route as AppPropertiesIdExposeRouteImport } from './routes/_app/properties.$id.expose'
import { Route as AppFinancingIdQuickCheckResultRouteImport } from './routes/_app/financing.$id.quick-check-result'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OaaxRoute = OaaxRouteImport.update({
  id: '/oaax',
  path: '/oaax',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const InviteIndexRoute = InviteIndexRouteImport.update({
  id: '/invite/',
  path: '/invite/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelbstauskunftTokenRoute = SelbstauskunftTokenRouteImport.update({
  id: '/selbstauskunft/$token',
  path: '/selbstauskunft/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSecurityRoute = PlatformSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformModulesRoute = PlatformModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformFeedbackRoute = PlatformFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDomainsRoute = PlatformDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformCommercialRoute = PlatformCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformActivityRoute = PlatformActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PlatformRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzierungTokenRoute = FinanzierungTokenRouteImport.update({
  id: '/finanzierung/$token',
  path: '/finanzierung/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BankPaketTokenRoute = BankPaketTokenRouteImport.update({
  id: '/bank-paket/$token',
  path: '/bank-paket/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReservationsRoute = AppReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNdasRoute = AppNdasRouteImport.update({
  id: '/ndas',
  path: '/ndas',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchingRoute = AppMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AppRoute,
} as any)
const AppMandatesRoute = AppMandatesRouteImport.update({
  id: '/mandates',
  path: '/mandates',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppGeneratedDocumentsRoute = AppGeneratedDocumentsRouteImport.update({
  id: '/generated-documents',
  path: '/generated-documents',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppExposesRoute = AppExposesRouteImport.update({
  id: '/exposes',
  path: '/exposes',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistsRoute = AppChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const PlatformTenantsIndexRoute = PlatformTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => PlatformRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPropertiesIndexRoute = AppPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppFinancingIndexRoute = AppFinancingIndexRouteImport.update({
  id: '/financing/',
  path: '/financing/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const PlatformTenantsAgencyIdRoute = PlatformTenantsAgencyIdRouteImport.update({
  id: '/tenants/$agencyId',
  path: '/tenants/$agencyId',
  getParentRoute: () => PlatformRoute,
} as any)
const ApiPublicPortalWebhookRoute = ApiPublicPortalWebhookRouteImport.update({
  id: '/api/public/portal-webhook',
  path: '/api/public/portal-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsWhiteLabelRoute = AppSettingsWhiteLabelRouteImport.update({
  id: '/white-label',
  path: '/white-label',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsVideoRoute = AppSettingsVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTrashRoute = AppSettingsTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsModulesRoute = AppSettingsModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsEsignRoute = AppSettingsEsignRouteImport.update({
  id: '/esign',
  path: '/esign',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCategoriesRoute = AppSettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsCalendarRoute = AppSettingsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBrandkitRoute = AppSettingsBrandkitRouteImport.update({
  id: '/brandkit',
  path: '/brandkit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBanksRoute = AppSettingsBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPropertiesIdRoute = AppPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetRoomRoute = AppMeetRoomRouteImport.update({
  id: '/meet/$room',
  path: '/meet/$room',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLeadsRoute,
} as any)
const AppFinancingIdRoute = AppFinancingIdRouteImport.update({
  id: '/financing/$id',
  path: '/financing/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMsCalendarWorkerRoute =
  ApiPublicMsCalendarWorkerRouteImport.update({
    id: '/api/public/ms-calendar/worker',
    path: '/api/public/ms-calendar/worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMsCalendarNotificationsRoute =
  ApiPublicMsCalendarNotificationsRouteImport.update({
    id: '/api/public/ms-calendar/notifications',
    path: '/api/public/ms-calendar/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMsCalendarCallbackRoute =
  ApiPublicMsCalendarCallbackRouteImport.update({
    id: '/api/public/ms-calendar/callback',
    path: '/api/public/ms-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBankPaketTokenRoute = ApiPublicBankPaketTokenRouteImport.update({
  id: '/api/public/bank-paket/$token',
  path: '/api/public/bank-paket/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPropertiesIdExposeRoute = AppPropertiesIdExposeRouteImport.update({
  id: '/expose',
  path: '/expose',
  getParentRoute: () => AppPropertiesIdRoute,
} as any)
const AppFinancingIdQuickCheckResultRoute =
  AppFinancingIdQuickCheckResultRouteImport.update({
    id: '/quick-check-result',
    path: '/quick-check-result',
    getParentRoute: () => AppFinancingIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/platform': typeof PlatformRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/checklists': typeof AppChecklistsRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/commissions': typeof AppCommissionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRoute
  '/documents': typeof AppDocumentsRoute
  '/exposes': typeof AppExposesRoute
  '/feedback': typeof AppFeedbackRoute
  '/generated-documents': typeof AppGeneratedDocumentsRoute
  '/leads': typeof AppLeadsRouteWithChildren
  '/mandates': typeof AppMandatesRoute
  '/matching': typeof AppMatchingRoute
  '/media': typeof AppMediaRoute
  '/ndas': typeof AppNdasRoute
  '/notifications': typeof AppNotificationsRoute
  '/reservations': typeof AppReservationsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/tasks': typeof AppTasksRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/bank-paket/$token': typeof BankPaketTokenRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/commercial': typeof PlatformCommercialRoute
  '/platform/domains': typeof PlatformDomainsRoute
  '/platform/feedback': typeof PlatformFeedbackRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/security': typeof PlatformSecurityRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/selbstauskunft/$token': typeof SelbstauskunftTokenRoute
  '/invite/': typeof InviteIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/financing/$id': typeof AppFinancingIdRouteWithChildren
  '/leads/$id': typeof AppLeadsIdRoute
  '/meet/$room': typeof AppMeetRoomRoute
  '/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/settings/banks': typeof AppSettingsBanksRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/brandkit': typeof AppSettingsBrandkitRoute
  '/settings/calendar': typeof AppSettingsCalendarRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/esign': typeof AppSettingsEsignRoute
  '/settings/modules': typeof AppSettingsModulesRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/trash': typeof AppSettingsTrashRoute
  '/settings/video': typeof AppSettingsVideoRoute
  '/settings/white-label': typeof AppSettingsWhiteLabelRoute
  '/api/public/portal-webhook': typeof ApiPublicPortalWebhookRoute
  '/platform/tenants/$agencyId': typeof PlatformTenantsAgencyIdRoute
  '/clients/': typeof AppClientsIndexRoute
  '/financing/': typeof AppFinancingIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/properties/': typeof AppPropertiesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/platform/tenants/': typeof PlatformTenantsIndexRoute
  '/financing/$id/quick-check-result': typeof AppFinancingIdQuickCheckResultRoute
  '/properties/$id/expose': typeof AppPropertiesIdExposeRoute
  '/api/public/bank-paket/$token': typeof ApiPublicBankPaketTokenRoute
  '/api/public/ms-calendar/callback': typeof ApiPublicMsCalendarCallbackRoute
  '/api/public/ms-calendar/notifications': typeof ApiPublicMsCalendarNotificationsRoute
  '/api/public/ms-calendar/worker': typeof ApiPublicMsCalendarWorkerRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/set-password': typeof SetPasswordRoute
  '/analytics': typeof AppAnalyticsRoute
  '/appointments': typeof AppAppointmentsRoute
  '/checklists': typeof AppChecklistsRoute
  '/commissions': typeof AppCommissionsRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRoute
  '/documents': typeof AppDocumentsRoute
  '/exposes': typeof AppExposesRoute
  '/feedback': typeof AppFeedbackRoute
  '/generated-documents': typeof AppGeneratedDocumentsRoute
  '/mandates': typeof AppMandatesRoute
  '/matching': typeof AppMatchingRoute
  '/media': typeof AppMediaRoute
  '/ndas': typeof AppNdasRoute
  '/notifications': typeof AppNotificationsRoute
  '/reservations': typeof AppReservationsRoute
  '/tasks': typeof AppTasksRoute
  '/team': typeof AppTeamRoute
  '/templates': typeof AppTemplatesRoute
  '/bank-paket/$token': typeof BankPaketTokenRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/commercial': typeof PlatformCommercialRoute
  '/platform/domains': typeof PlatformDomainsRoute
  '/platform/feedback': typeof PlatformFeedbackRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/security': typeof PlatformSecurityRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/selbstauskunft/$token': typeof SelbstauskunftTokenRoute
  '/invite': typeof InviteIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/financing/$id': typeof AppFinancingIdRouteWithChildren
  '/leads/$id': typeof AppLeadsIdRoute
  '/meet/$room': typeof AppMeetRoomRoute
  '/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/settings/banks': typeof AppSettingsBanksRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/brandkit': typeof AppSettingsBrandkitRoute
  '/settings/calendar': typeof AppSettingsCalendarRoute
  '/settings/categories': typeof AppSettingsCategoriesRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/esign': typeof AppSettingsEsignRoute
  '/settings/modules': typeof AppSettingsModulesRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/trash': typeof AppSettingsTrashRoute
  '/settings/video': typeof AppSettingsVideoRoute
  '/settings/white-label': typeof AppSettingsWhiteLabelRoute
  '/api/public/portal-webhook': typeof ApiPublicPortalWebhookRoute
  '/platform/tenants/$agencyId': typeof PlatformTenantsAgencyIdRoute
  '/clients': typeof AppClientsIndexRoute
  '/financing': typeof AppFinancingIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/properties': typeof AppPropertiesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/platform/tenants': typeof PlatformTenantsIndexRoute
  '/financing/$id/quick-check-result': typeof AppFinancingIdQuickCheckResultRoute
  '/properties/$id/expose': typeof AppPropertiesIdExposeRoute
  '/api/public/bank-paket/$token': typeof ApiPublicBankPaketTokenRoute
  '/api/public/ms-calendar/callback': typeof ApiPublicMsCalendarCallbackRoute
  '/api/public/ms-calendar/notifications': typeof ApiPublicMsCalendarNotificationsRoute
  '/api/public/ms-calendar/worker': typeof ApiPublicMsCalendarWorkerRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/oaax': typeof OaaxRoute
  '/platform': typeof PlatformRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/checklists': typeof AppChecklistsRoute
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/commissions': typeof AppCommissionsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/exposes': typeof AppExposesRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/generated-documents': typeof AppGeneratedDocumentsRoute
  '/_app/leads': typeof AppLeadsRouteWithChildren
  '/_app/mandates': typeof AppMandatesRoute
  '/_app/matching': typeof AppMatchingRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/ndas': typeof AppNdasRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/reservations': typeof AppReservationsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/tasks': typeof AppTasksRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/bank-paket/$token': typeof BankPaketTokenRoute
  '/finanzierung/$token': typeof FinanzierungTokenRoute
  '/invite/$token': typeof InviteTokenRoute
  '/p/$token': typeof PTokenRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/commercial': typeof PlatformCommercialRoute
  '/platform/domains': typeof PlatformDomainsRoute
  '/platform/feedback': typeof PlatformFeedbackRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/security': typeof PlatformSecurityRoute
  '/platform/settings': typeof PlatformSettingsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/selbstauskunft/$token': typeof SelbstauskunftTokenRoute
  '/invite/': typeof InviteIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/financing/$id': typeof AppFinancingIdRouteWithChildren
  '/_app/leads/$id': typeof AppLeadsIdRoute
  '/_app/meet/$room': typeof AppMeetRoomRoute
  '/_app/properties/$id': typeof AppPropertiesIdRouteWithChildren
  '/_app/settings/banks': typeof AppSettingsBanksRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/brandkit': typeof AppSettingsBrandkitRoute
  '/_app/settings/calendar': typeof AppSettingsCalendarRoute
  '/_app/settings/categories': typeof AppSettingsCategoriesRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/esign': typeof AppSettingsEsignRoute
  '/_app/settings/modules': typeof AppSettingsModulesRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/trash': typeof AppSettingsTrashRoute
  '/_app/settings/video': typeof AppSettingsVideoRoute
  '/_app/settings/white-label': typeof AppSettingsWhiteLabelRoute
  '/api/public/portal-webhook': typeof ApiPublicPortalWebhookRoute
  '/platform/tenants/$agencyId': typeof PlatformTenantsAgencyIdRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/financing/': typeof AppFinancingIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/properties/': typeof AppPropertiesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/platform/tenants/': typeof PlatformTenantsIndexRoute
  '/_app/financing/$id/quick-check-result': typeof AppFinancingIdQuickCheckResultRoute
  '/_app/properties/$id/expose': typeof AppPropertiesIdExposeRoute
  '/api/public/bank-paket/$token': typeof ApiPublicBankPaketTokenRoute
  '/api/public/ms-calendar/callback': typeof ApiPublicMsCalendarCallbackRoute
  '/api/public/ms-calendar/notifications': typeof ApiPublicMsCalendarNotificationsRoute
  '/api/public/ms-calendar/worker': typeof ApiPublicMsCalendarWorkerRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/oaax'
    | '/platform'
    | '/set-password'
    | '/analytics'
    | '/appointments'
    | '/checklists'
    | '/clients'
    | '/commissions'
    | '/dashboard'
    | '/docs'
    | '/documents'
    | '/exposes'
    | '/feedback'
    | '/generated-documents'
    | '/leads'
    | '/mandates'
    | '/matching'
    | '/media'
    | '/ndas'
    | '/notifications'
    | '/reservations'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/templates'
    | '/bank-paket/$token'
    | '/finanzierung/$token'
    | '/invite/$token'
    | '/p/$token'
    | '/platform/activity'
    | '/platform/commercial'
    | '/platform/domains'
    | '/platform/feedback'
    | '/platform/modules'
    | '/platform/security'
    | '/platform/settings'
    | '/platform/users'
    | '/selbstauskunft/$token'
    | '/invite/'
    | '/platform/'
    | '/clients/$id'
    | '/financing/$id'
    | '/leads/$id'
    | '/meet/$room'
    | '/properties/$id'
    | '/settings/banks'
    | '/settings/billing'
    | '/settings/brandkit'
    | '/settings/calendar'
    | '/settings/categories'
    | '/settings/company'
    | '/settings/esign'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/trash'
    | '/settings/video'
    | '/settings/white-label'
    | '/api/public/portal-webhook'
    | '/platform/tenants/$agencyId'
    | '/clients/'
    | '/financing/'
    | '/leads/'
    | '/properties/'
    | '/settings/'
    | '/platform/tenants/'
    | '/financing/$id/quick-check-result'
    | '/properties/$id/expose'
    | '/api/public/bank-paket/$token'
    | '/api/public/ms-calendar/callback'
    | '/api/public/ms-calendar/notifications'
    | '/api/public/ms-calendar/worker'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/oaax'
    | '/set-password'
    | '/analytics'
    | '/appointments'
    | '/checklists'
    | '/commissions'
    | '/dashboard'
    | '/docs'
    | '/documents'
    | '/exposes'
    | '/feedback'
    | '/generated-documents'
    | '/mandates'
    | '/matching'
    | '/media'
    | '/ndas'
    | '/notifications'
    | '/reservations'
    | '/tasks'
    | '/team'
    | '/templates'
    | '/bank-paket/$token'
    | '/finanzierung/$token'
    | '/invite/$token'
    | '/p/$token'
    | '/platform/activity'
    | '/platform/commercial'
    | '/platform/domains'
    | '/platform/feedback'
    | '/platform/modules'
    | '/platform/security'
    | '/platform/settings'
    | '/platform/users'
    | '/selbstauskunft/$token'
    | '/invite'
    | '/platform'
    | '/clients/$id'
    | '/financing/$id'
    | '/leads/$id'
    | '/meet/$room'
    | '/properties/$id'
    | '/settings/banks'
    | '/settings/billing'
    | '/settings/brandkit'
    | '/settings/calendar'
    | '/settings/categories'
    | '/settings/company'
    | '/settings/esign'
    | '/settings/modules'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/trash'
    | '/settings/video'
    | '/settings/white-label'
    | '/api/public/portal-webhook'
    | '/platform/tenants/$agencyId'
    | '/clients'
    | '/financing'
    | '/leads'
    | '/properties'
    | '/settings'
    | '/platform/tenants'
    | '/financing/$id/quick-check-result'
    | '/properties/$id/expose'
    | '/api/public/bank-paket/$token'
    | '/api/public/ms-calendar/callback'
    | '/api/public/ms-calendar/notifications'
    | '/api/public/ms-calendar/worker'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/oaax'
    | '/platform'
    | '/set-password'
    | '/_app/analytics'
    | '/_app/appointments'
    | '/_app/checklists'
    | '/_app/clients'
    | '/_app/commissions'
    | '/_app/dashboard'
    | '/_app/docs'
    | '/_app/documents'
    | '/_app/exposes'
    | '/_app/feedback'
    | '/_app/generated-documents'
    | '/_app/leads'
    | '/_app/mandates'
    | '/_app/matching'
    | '/_app/media'
    | '/_app/ndas'
    | '/_app/notifications'
    | '/_app/reservations'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/team'
    | '/_app/templates'
    | '/bank-paket/$token'
    | '/finanzierung/$token'
    | '/invite/$token'
    | '/p/$token'
    | '/platform/activity'
    | '/platform/commercial'
    | '/platform/domains'
    | '/platform/feedback'
    | '/platform/modules'
    | '/platform/security'
    | '/platform/settings'
    | '/platform/users'
    | '/selbstauskunft/$token'
    | '/invite/'
    | '/platform/'
    | '/_app/clients/$id'
    | '/_app/financing/$id'
    | '/_app/leads/$id'
    | '/_app/meet/$room'
    | '/_app/properties/$id'
    | '/_app/settings/banks'
    | '/_app/settings/billing'
    | '/_app/settings/brandkit'
    | '/_app/settings/calendar'
    | '/_app/settings/categories'
    | '/_app/settings/company'
    | '/_app/settings/esign'
    | '/_app/settings/modules'
    | '/_app/settings/notifications'
    | '/_app/settings/profile'
    | '/_app/settings/trash'
    | '/_app/settings/video'
    | '/_app/settings/white-label'
    | '/api/public/portal-webhook'
    | '/platform/tenants/$agencyId'
    | '/_app/clients/'
    | '/_app/financing/'
    | '/_app/leads/'
    | '/_app/properties/'
    | '/_app/settings/'
    | '/platform/tenants/'
    | '/_app/financing/$id/quick-check-result'
    | '/_app/properties/$id/expose'
    | '/api/public/bank-paket/$token'
    | '/api/public/ms-calendar/callback'
    | '/api/public/ms-calendar/notifications'
    | '/api/public/ms-calendar/worker'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OaaxRoute: typeof OaaxRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  SetPasswordRoute: typeof SetPasswordRoute
  BankPaketTokenRoute: typeof BankPaketTokenRoute
  FinanzierungTokenRoute: typeof FinanzierungTokenRoute
  InviteTokenRoute: typeof InviteTokenRoute
  PTokenRoute: typeof PTokenRoute
  SelbstauskunftTokenRoute: typeof SelbstauskunftTokenRoute
  InviteIndexRoute: typeof InviteIndexRoute
  ApiPublicPortalWebhookRoute: typeof ApiPublicPortalWebhookRoute
  ApiPublicBankPaketTokenRoute: typeof ApiPublicBankPaketTokenRoute
  ApiPublicMsCalendarCallbackRoute: typeof ApiPublicMsCalendarCallbackRoute
  ApiPublicMsCalendarNotificationsRoute: typeof ApiPublicMsCalendarNotificationsRoute
  ApiPublicMsCalendarWorkerRoute: typeof ApiPublicMsCalendarWorkerRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oaax': {
      id: '/oaax'
      path: '/oaax'
      fullPath: '/oaax'
      preLoaderRoute: typeof OaaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/invite/': {
      id: '/invite/'
      path: '/invite'
      fullPath: '/invite/'
      preLoaderRoute: typeof InviteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selbstauskunft/$token': {
      id: '/selbstauskunft/$token'
      path: '/selbstauskunft/$token'
      fullPath: '/selbstauskunft/$token'
      preLoaderRoute: typeof SelbstauskunftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/users': {
      id: '/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/security': {
      id: '/platform/security'
      path: '/security'
      fullPath: '/platform/security'
      preLoaderRoute: typeof PlatformSecurityRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/modules': {
      id: '/platform/modules'
      path: '/modules'
      fullPath: '/platform/modules'
      preLoaderRoute: typeof PlatformModulesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/feedback': {
      id: '/platform/feedback'
      path: '/feedback'
      fullPath: '/platform/feedback'
      preLoaderRoute: typeof PlatformFeedbackRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/domains': {
      id: '/platform/domains'
      path: '/domains'
      fullPath: '/platform/domains'
      preLoaderRoute: typeof PlatformDomainsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/commercial': {
      id: '/platform/commercial'
      path: '/commercial'
      fullPath: '/platform/commercial'
      preLoaderRoute: typeof PlatformCommercialRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/activity': {
      id: '/platform/activity'
      path: '/activity'
      fullPath: '/platform/activity'
      preLoaderRoute: typeof PlatformActivityRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzierung/$token': {
      id: '/finanzierung/$token'
      path: '/finanzierung/$token'
      fullPath: '/finanzierung/$token'
      preLoaderRoute: typeof FinanzierungTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-paket/$token': {
      id: '/bank-paket/$token'
      path: '/bank-paket/$token'
      fullPath: '/bank-paket/$token'
      preLoaderRoute: typeof BankPaketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservations': {
      id: '/_app/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AppReservationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ndas': {
      id: '/_app/ndas'
      path: '/ndas'
      fullPath: '/ndas'
      preLoaderRoute: typeof AppNdasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matching': {
      id: '/_app/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof AppMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mandates': {
      id: '/_app/mandates'
      path: '/mandates'
      fullPath: '/mandates'
      preLoaderRoute: typeof AppMandatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/generated-documents': {
      id: '/_app/generated-documents'
      path: '/generated-documents'
      fullPath: '/generated-documents'
      preLoaderRoute: typeof AppGeneratedDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exposes': {
      id: '/_app/exposes'
      path: '/exposes'
      fullPath: '/exposes'
      preLoaderRoute: typeof AppExposesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commissions': {
      id: '/_app/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklists': {
      id: '/_app/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AppChecklistsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/platform/tenants/': {
      id: '/platform/tenants/'
      path: '/tenants'
      fullPath: '/platform/tenants/'
      preLoaderRoute: typeof PlatformTenantsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/properties/': {
      id: '/_app/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/financing/': {
      id: '/_app/financing/'
      path: '/financing'
      fullPath: '/financing/'
      preLoaderRoute: typeof AppFinancingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/platform/tenants/$agencyId': {
      id: '/platform/tenants/$agencyId'
      path: '/tenants/$agencyId'
      fullPath: '/platform/tenants/$agencyId'
      preLoaderRoute: typeof PlatformTenantsAgencyIdRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/api/public/portal-webhook': {
      id: '/api/public/portal-webhook'
      path: '/api/public/portal-webhook'
      fullPath: '/api/public/portal-webhook'
      preLoaderRoute: typeof ApiPublicPortalWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/white-label': {
      id: '/_app/settings/white-label'
      path: '/white-label'
      fullPath: '/settings/white-label'
      preLoaderRoute: typeof AppSettingsWhiteLabelRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/video': {
      id: '/_app/settings/video'
      path: '/video'
      fullPath: '/settings/video'
      preLoaderRoute: typeof AppSettingsVideoRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/trash': {
      id: '/_app/settings/trash'
      path: '/trash'
      fullPath: '/settings/trash'
      preLoaderRoute: typeof AppSettingsTrashRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/modules': {
      id: '/_app/settings/modules'
      path: '/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof AppSettingsModulesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/esign': {
      id: '/_app/settings/esign'
      path: '/esign'
      fullPath: '/settings/esign'
      preLoaderRoute: typeof AppSettingsEsignRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/categories': {
      id: '/_app/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof AppSettingsCategoriesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/calendar': {
      id: '/_app/settings/calendar'
      path: '/calendar'
      fullPath: '/settings/calendar'
      preLoaderRoute: typeof AppSettingsCalendarRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/brandkit': {
      id: '/_app/settings/brandkit'
      path: '/brandkit'
      fullPath: '/settings/brandkit'
      preLoaderRoute: typeof AppSettingsBrandkitRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/banks': {
      id: '/_app/settings/banks'
      path: '/banks'
      fullPath: '/settings/banks'
      preLoaderRoute: typeof AppSettingsBanksRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/properties/$id': {
      id: '/_app/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AppPropertiesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meet/$room': {
      id: '/_app/meet/$room'
      path: '/meet/$room'
      fullPath: '/meet/$room'
      preLoaderRoute: typeof AppMeetRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$id': {
      id: '/_app/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppLeadsRoute
    }
    '/_app/financing/$id': {
      id: '/_app/financing/$id'
      path: '/financing/$id'
      fullPath: '/financing/$id'
      preLoaderRoute: typeof AppFinancingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ms-calendar/worker': {
      id: '/api/public/ms-calendar/worker'
      path: '/api/public/ms-calendar/worker'
      fullPath: '/api/public/ms-calendar/worker'
      preLoaderRoute: typeof ApiPublicMsCalendarWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ms-calendar/notifications': {
      id: '/api/public/ms-calendar/notifications'
      path: '/api/public/ms-calendar/notifications'
      fullPath: '/api/public/ms-calendar/notifications'
      preLoaderRoute: typeof ApiPublicMsCalendarNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ms-calendar/callback': {
      id: '/api/public/ms-calendar/callback'
      path: '/api/public/ms-calendar/callback'
      fullPath: '/api/public/ms-calendar/callback'
      preLoaderRoute: typeof ApiPublicMsCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bank-paket/$token': {
      id: '/api/public/bank-paket/$token'
      path: '/api/public/bank-paket/$token'
      fullPath: '/api/public/bank-paket/$token'
      preLoaderRoute: typeof ApiPublicBankPaketTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/properties/$id/expose': {
      id: '/_app/properties/$id/expose'
      path: '/expose'
      fullPath: '/properties/$id/expose'
      preLoaderRoute: typeof AppPropertiesIdExposeRouteImport
      parentRoute: typeof AppPropertiesIdRoute
    }
    '/_app/financing/$id/quick-check-result': {
      id: '/_app/financing/$id/quick-check-result'
      path: '/quick-check-result'
      fullPath: '/financing/$id/quick-check-result'
      preLoaderRoute: typeof AppFinancingIdQuickCheckResultRouteImport
      parentRoute: typeof AppFinancingIdRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppLeadsRouteChildren {
  AppLeadsIdRoute: typeof AppLeadsIdRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppLeadsRouteChildren: AppLeadsRouteChildren = {
  AppLeadsIdRoute: AppLeadsIdRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppLeadsRouteWithChildren = AppLeadsRoute._addFileChildren(
  AppLeadsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsBanksRoute: typeof AppSettingsBanksRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsBrandkitRoute: typeof AppSettingsBrandkitRoute
  AppSettingsCalendarRoute: typeof AppSettingsCalendarRoute
  AppSettingsCategoriesRoute: typeof AppSettingsCategoriesRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsEsignRoute: typeof AppSettingsEsignRoute
  AppSettingsModulesRoute: typeof AppSettingsModulesRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsTrashRoute: typeof AppSettingsTrashRoute
  AppSettingsVideoRoute: typeof AppSettingsVideoRoute
  AppSettingsWhiteLabelRoute: typeof AppSettingsWhiteLabelRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsBanksRoute: AppSettingsBanksRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsBrandkitRoute: AppSettingsBrandkitRoute,
  AppSettingsCalendarRoute: AppSettingsCalendarRoute,
  AppSettingsCategoriesRoute: AppSettingsCategoriesRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsEsignRoute: AppSettingsEsignRoute,
  AppSettingsModulesRoute: AppSettingsModulesRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsTrashRoute: AppSettingsTrashRoute,
  AppSettingsVideoRoute: AppSettingsVideoRoute,
  AppSettingsWhiteLabelRoute: AppSettingsWhiteLabelRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppFinancingIdRouteChildren {
  AppFinancingIdQuickCheckResultRoute: typeof AppFinancingIdQuickCheckResultRoute
}

const AppFinancingIdRouteChildren: AppFinancingIdRouteChildren = {
  AppFinancingIdQuickCheckResultRoute: AppFinancingIdQuickCheckResultRoute,
}

const AppFinancingIdRouteWithChildren = AppFinancingIdRoute._addFileChildren(
  AppFinancingIdRouteChildren,
)

interface AppPropertiesIdRouteChildren {
  AppPropertiesIdExposeRoute: typeof AppPropertiesIdExposeRoute
}

const AppPropertiesIdRouteChildren: AppPropertiesIdRouteChildren = {
  AppPropertiesIdExposeRoute: AppPropertiesIdExposeRoute,
}

const AppPropertiesIdRouteWithChildren = AppPropertiesIdRoute._addFileChildren(
  AppPropertiesIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppChecklistsRoute: typeof AppChecklistsRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocsRoute: typeof AppDocsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppExposesRoute: typeof AppExposesRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppGeneratedDocumentsRoute: typeof AppGeneratedDocumentsRoute
  AppLeadsRoute: typeof AppLeadsRouteWithChildren
  AppMandatesRoute: typeof AppMandatesRoute
  AppMatchingRoute: typeof AppMatchingRoute
  AppMediaRoute: typeof AppMediaRoute
  AppNdasRoute: typeof AppNdasRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReservationsRoute: typeof AppReservationsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppFinancingIdRoute: typeof AppFinancingIdRouteWithChildren
  AppMeetRoomRoute: typeof AppMeetRoomRoute
  AppPropertiesIdRoute: typeof AppPropertiesIdRouteWithChildren
  AppFinancingIndexRoute: typeof AppFinancingIndexRoute
  AppPropertiesIndexRoute: typeof AppPropertiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppChecklistsRoute: AppChecklistsRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppCommissionsRoute: AppCommissionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocsRoute: AppDocsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppExposesRoute: AppExposesRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppGeneratedDocumentsRoute: AppGeneratedDocumentsRoute,
  AppLeadsRoute: AppLeadsRouteWithChildren,
  AppMandatesRoute: AppMandatesRoute,
  AppMatchingRoute: AppMatchingRoute,
  AppMediaRoute: AppMediaRoute,
  AppNdasRoute: AppNdasRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReservationsRoute: AppReservationsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppFinancingIdRoute: AppFinancingIdRouteWithChildren,
  AppMeetRoomRoute: AppMeetRoomRoute,
  AppPropertiesIdRoute: AppPropertiesIdRouteWithChildren,
  AppFinancingIndexRoute: AppFinancingIndexRoute,
  AppPropertiesIndexRoute: AppPropertiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformRouteChildren {
  PlatformActivityRoute: typeof PlatformActivityRoute
  PlatformCommercialRoute: typeof PlatformCommercialRoute
  PlatformDomainsRoute: typeof PlatformDomainsRoute
  PlatformFeedbackRoute: typeof PlatformFeedbackRoute
  PlatformModulesRoute: typeof PlatformModulesRoute
  PlatformSecurityRoute: typeof PlatformSecurityRoute
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformUsersRoute: typeof PlatformUsersRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformTenantsAgencyIdRoute: typeof PlatformTenantsAgencyIdRoute
  PlatformTenantsIndexRoute: typeof PlatformTenantsIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformActivityRoute: PlatformActivityRoute,
  PlatformCommercialRoute: PlatformCommercialRoute,
  PlatformDomainsRoute: PlatformDomainsRoute,
  PlatformFeedbackRoute: PlatformFeedbackRoute,
  PlatformModulesRoute: PlatformModulesRoute,
  PlatformSecurityRoute: PlatformSecurityRoute,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformUsersRoute: PlatformUsersRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformTenantsAgencyIdRoute: PlatformTenantsAgencyIdRoute,
  PlatformTenantsIndexRoute: PlatformTenantsIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OaaxRoute: OaaxRoute,
  PlatformRoute: PlatformRouteWithChildren,
  SetPasswordRoute: SetPasswordRoute,
  BankPaketTokenRoute: BankPaketTokenRoute,
  FinanzierungTokenRoute: FinanzierungTokenRoute,
  InviteTokenRoute: InviteTokenRoute,
  PTokenRoute: PTokenRoute,
  SelbstauskunftTokenRoute: SelbstauskunftTokenRoute,
  InviteIndexRoute: InviteIndexRoute,
  ApiPublicPortalWebhookRoute: ApiPublicPortalWebhookRoute,
  ApiPublicBankPaketTokenRoute: ApiPublicBankPaketTokenRoute,
  ApiPublicMsCalendarCallbackRoute: ApiPublicMsCalendarCallbackRoute,
  ApiPublicMsCalendarNotificationsRoute: ApiPublicMsCalendarNotificationsRoute,
  ApiPublicMsCalendarWorkerRoute: ApiPublicMsCalendarWorkerRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
